
/*
 *  This file was generated by the SOM Compiler.
 *  Generated using:
 *     SOM incremental update: 2.47
 */


/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using template emitter:
 *      SOM Emitter emitxtm: 2.23.1.9
 */

#ifndef SOM_Module_devcpu_Source
#define SOM_Module_devcpu_Source
#endif
#define WPDevCPUEx_Class_Source
#define M_WPDevCPUEx_Class_Source

#define _RETAIL /* to completely eliminate the ...MethodDebug(...) debugging output to SOMOutCharRoutine (default:stdout) */
#include "devcpu.xih"
#include "resources.h"


SOM_Scope void SOMLINK somDefaultInit(WPDevCPUEx *somSelf, som3InitCtrl* ctrl)
{
    WPDevCPUExData *somThis; /* set in BeginInitializer */
    somInitCtrl globalCtrl;
    somBooleanVector myMask;
    WPDevCPUExMethodDebug("WPDevCPUEx","somDefaultInit");
    WPDevCPUEx_BeginInitializer_somDefaultInit;

    WPDevCPUEx_Init_WPDevCPU_somDefaultInit(somSelf, ctrl);

    /*
     * local WPDevCPUEx initialization code added by programmer
     */
}


SOM_Scope void SOMLINK somDestruct(WPDevCPUEx *somSelf, octet doFree, 
                                   som3DestructCtrl* ctrl)
{
    WPDevCPUExData *somThis; /* set in BeginDestructor */
    somDestructCtrl globalCtrl;
    somBooleanVector myMask;
    WPDevCPUExMethodDebug("WPDevCPUEx","somDestruct");
    WPDevCPUEx_BeginDestructor;

    /*
     * local WPDevCPUEx deinitialization code added by programmer
     */

    WPDevCPUEx_EndDestructor;
}


SOM_Scope ULONG  SOMLINK wpAddDeviceDMA1Page(WPDevCPUEx *somSelf, 
                                             HWND hwndNotebook)
{
    /* WPDevCPUExData *somThis = WPDevCPUExGetData(somSelf); */
    WPDevCPUExMethodDebug("WPDevCPUEx","wpAddDeviceDMA1Page");
  
    return SETTINGS_PAGE_REMOVED;
}

SOM_Scope ULONG  SOMLINK wpAddDeviceIO1Page(WPDevCPUEx *somSelf, 
                                            HWND hwndNotebook)
{
    /* WPDevCPUExData *somThis = WPDevCPUExGetData(somSelf); */
    WPDevCPUExMethodDebug("WPDevCPUEx","wpAddDeviceIO1Page");

    return SETTINGS_PAGE_REMOVED;
}

SOM_Scope ULONG  SOMLINK wpAddDeviceIRQ1Page(WPDevCPUEx *somSelf, 
                                             HWND hwndNotebook)
{
    /* WPDevCPUExData *somThis = WPDevCPUExGetData(somSelf); */
    WPDevCPUExMethodDebug("WPDevCPUEx","wpAddDeviceIRQ1Page");

    return SETTINGS_PAGE_REMOVED;
}

SOM_Scope ULONG  SOMLINK wpAddDeviceMemory1Page(WPDevCPUEx *somSelf, 
                                                HWND hwndNotebook)
{
    /* WPDevCPUExData *somThis = WPDevCPUExGetData(somSelf); */
    WPDevCPUExMethodDebug("WPDevCPUEx","wpAddDeviceMemory1Page");

    return SETTINGS_PAGE_REMOVED;
}


extern HMODULE gModule;

MRESULT EXPENTRY FeaturePageDlg(HWND hwndDlg,ULONG msg,MPARAM mp1,MPARAM mp2)
{
   switch(msg)
   {
       case WM_INITDLG:
          WinSetWindowText(WinWindowFromID(hwndDlg,STATICTEXT),"Hallo");
          break;
   }

   return WinDefDlgProc(hwndDlg,msg,mp1,mp2);
}

SOM_Scope BOOL  SOMLINK wpAddSettingsPages(WPDevCPUEx *somSelf, 
                                           HWND hwndNotebook)
{
    PAGEINFO pageinfo;
    BOOL rc;

    /* WPDevCPUExData *somThis = WPDevCPUExGetData(somSelf); */
    WPDevCPUExMethodDebug("WPDevCPUEx","wpAddSettingsPages");

    (WPDevCPUEx_parent_WPDevCPU_wpAddSettingsPages(somSelf, 
                                                   hwndNotebook));

    memset(&pageinfo,0,sizeof(pageinfo));
    pageinfo.cb                 = sizeof(pageinfo);
    pageinfo.usPageStyleFlags   = BKA_MAJOR;
    pageinfo.usPageInsertFlags  = BKA_FIRST;
    pageinfo.pfnwp              = FeaturePageDlg;
    pageinfo.resid              = gModule;
    pageinfo.dlgid              = DLGMAIN;
    pageinfo.pszName            = "Features";
     
    return somSelf->wpInsertSettingsPage(hwndNotebook,&pageinfo);
}
